# NumPy for Matlab Users (really?)


If you are a MATLAB&reg; user I do recommend to read [Numpy for MATLAB Users](https://docs.scipy.org/doc/numpy-1.15.0/user/numpy-for-matlab-users.html).

### Numpy can load and save native MATLAB® files:

In [1]:
import numpy as np

---

### The `Matrix` Array Type

In addition to the `numpy.ndarray` type, NumPy also support a very specific data type called `Matrix`. 

This special type of object has been introduced to allow for API and programming compatibility with
MATLAB®. 

**Note**: The most relevant feature of this new _array type_ is the behavior of the standard arithmetic operators `+, -, *` to use matrix algebra, which work as they would in MATLAB.

In [2]:
from numpy import matrix

In [3]:
a = np.arange(0, 5)
A = np.array([[n+m*10 for n in range(5)] for m in range(5)])

In [4]:
a

array([0, 1, 2, 3, 4])

In [5]:
A

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24],
       [30, 31, 32, 33, 34],
       [40, 41, 42, 43, 44]])

In [6]:
M = matrix(A)
v = matrix(a).T # make it a column vector

In [7]:
a

array([0, 1, 2, 3, 4])

In [8]:
M * M

matrix([[ 300,  310,  320,  330,  340],
        [1300, 1360, 1420, 1480, 1540],
        [2300, 2410, 2520, 2630, 2740],
        [3300, 3460, 3620, 3780, 3940],
        [4300, 4510, 4720, 4930, 5140]])

In [9]:
A @ A  # @ operator equivalent to np.dot(A, A)

array([[ 300,  310,  320,  330,  340],
       [1300, 1360, 1420, 1480, 1540],
       [2300, 2410, 2520, 2630, 2740],
       [3300, 3460, 3620, 3780, 3940],
       [4300, 4510, 4720, 4930, 5140]])

In [10]:
# Element wise multiplication in NumPy
A * A

array([[   0,    1,    4,    9,   16],
       [ 100,  121,  144,  169,  196],
       [ 400,  441,  484,  529,  576],
       [ 900,  961, 1024, 1089, 1156],
       [1600, 1681, 1764, 1849, 1936]])

In [11]:
M * v

matrix([[ 30],
        [130],
        [230],
        [330],
        [430]])

In [12]:
A * a

array([[  0,   1,   4,   9,  16],
       [  0,  11,  24,  39,  56],
       [  0,  21,  44,  69,  96],
       [  0,  31,  64,  99, 136],
       [  0,  41,  84, 129, 176]])

In [13]:
# inner product
v.T * v

matrix([[30]])

In [14]:
# with matrix objects, standard matrix algebra applies
v + M*v

matrix([[ 30],
        [131],
        [232],
        [333],
        [434]])

If we try to add, subtract or multiply objects with incomplatible shapes we get an error:

In [15]:
v_incompat = matrix(list(range(1, 7))).T

In [16]:
M.shape, v_incompat.shape

((5, 5), (6, 1))

In [17]:
M * v_incompat

ValueError: shapes (5,5) and (6,1) not aligned: 5 (dim 1) != 6 (dim 0)

See also the related functions: `inner`, `outer`, `cross`, `kron`, `tensordot`. 

Try for example `help(inner)`.

---

## Loading and Saving `.mat` file

Let's create a `numpy.ndarray` object

In [21]:
A = np.random.rand(10000, 300, 50)  # note: this may take a while

In [22]:
A

array([[[0.30788845, 0.60569692, 0.74159203, ..., 0.99513856,
         0.86615676, 0.65581839],
        [0.29972906, 0.1727805 , 0.73877596, ..., 0.57321798,
         0.52657155, 0.15148499],
        [0.91677054, 0.30289045, 0.47086303, ..., 0.91076997,
         0.15659756, 0.74502433],
        ...,
        [0.16246413, 0.57601666, 0.64519549, ..., 0.04166688,
         0.71115738, 0.75984878],
        [0.99626814, 0.89529207, 0.89520696, ..., 0.927474  ,
         0.46998733, 0.809978  ],
        [0.52545775, 0.42922203, 0.40999633, ..., 0.7497839 ,
         0.26582518, 0.68821719]],

       [[0.93763072, 0.68660253, 0.03060252, ..., 0.08489496,
         0.3368953 , 0.0040575 ],
        [0.17680589, 0.44922269, 0.32552186, ..., 0.49081397,
         0.7718607 , 0.91216332],
        [0.48935017, 0.28293444, 0.57762148, ..., 0.64988995,
         0.96036063, 0.62395338],
        ...,
        [0.77554755, 0.23174591, 0.80126054, ..., 0.34982511,
         0.13648038, 0.63953428],
        [0.4

### Introducing SciPy (ecosystem)

![scipy](images/scipy.png)

### `scipy.io`

In [20]:
from scipy import io as spio

### NumPy $\mapsto$ MATLAB :  `scipy.io.savemat`

In [23]:
spio.savemat('numpy_to.mat', {'A': A}, oned_as='row')  # savemat expects a dictionary

MATLAB $\mapsto$ NumPy: `scipy.io.loadmat`

In [24]:
data_dictionary = spio.loadmat('numpy_to.mat')


In [25]:
list(data_dictionary.keys())

['__header__', '__version__', '__globals__', 'A']

In [26]:
data_dictionary['A']

array([[[0.30788845, 0.60569692, 0.74159203, ..., 0.99513856,
         0.86615676, 0.65581839],
        [0.29972906, 0.1727805 , 0.73877596, ..., 0.57321798,
         0.52657155, 0.15148499],
        [0.91677054, 0.30289045, 0.47086303, ..., 0.91076997,
         0.15659756, 0.74502433],
        ...,
        [0.16246413, 0.57601666, 0.64519549, ..., 0.04166688,
         0.71115738, 0.75984878],
        [0.99626814, 0.89529207, 0.89520696, ..., 0.927474  ,
         0.46998733, 0.809978  ],
        [0.52545775, 0.42922203, 0.40999633, ..., 0.7497839 ,
         0.26582518, 0.68821719]],

       [[0.93763072, 0.68660253, 0.03060252, ..., 0.08489496,
         0.3368953 , 0.0040575 ],
        [0.17680589, 0.44922269, 0.32552186, ..., 0.49081397,
         0.7718607 , 0.91216332],
        [0.48935017, 0.28293444, 0.57762148, ..., 0.64988995,
         0.96036063, 0.62395338],
        ...,
        [0.77554755, 0.23174591, 0.80126054, ..., 0.34982511,
         0.13648038, 0.63953428],
        [0.4

In [27]:
A_load = data_dictionary['A']

In [28]:
np.all(A == A_load)

True

In [30]:
type(A_load)

numpy.ndarray