# Numexpr

**Numexpr** is a fast numerical expression evaluator for NumPy. 

With it, expressions that operate on arrays (like `3*a+4*b`) are accelerated and use less memory than doing the same calculation in Python.

In addition, its **multi-threaded capabilities** can make use of all your cores, which may accelerate computations, most specially if they are not memory-bounded.

Last but not least, `numexpr` can make use of Intel's VML (Vector Math Library, normally integrated in its Math Kernel Library, or MKL). This allows further acceleration of transcendent (i.e., non polynomial) expressions.

**GitHub**: [https://github.com/pydata/numexpr#what-it-is-numexpr]()

## Some Examples 

(gathered from `numexpr` documentation)

In [1]:
import numpy as np
import numexpr as ne

In [2]:
a = np.arange(1e6)   # Choose large arrays for better speedups
b = np.arange(1e6)

In [3]:
ne.evaluate("a + 1")   # a simple expression

array([  1.00000000e+00,   2.00000000e+00,   3.00000000e+00, ...,
         9.99998000e+05,   9.99999000e+05,   1.00000000e+06])

In [4]:
ne.evaluate('a*b-4.1*a > 2.5*b')   # a more complex one

array([False, False, False, ...,  True,  True,  True], dtype=bool)

In [5]:
ne.evaluate("sin(a) + arcsinh(a/b)")   # you can also use functions

array([        nan,  1.72284457,  1.79067101, ...,  1.09567006,
        0.17523598, -0.09597844])

## Time Comparison with Numpy

In [8]:
%timeit a+1

100 loops, best of 3: 3.11 ms per loop


In [9]:
%timeit ne.evaluate("a + 1")

100 loops, best of 3: 2.8 ms per loop


In [10]:
%timeit a*b-4.1*a > 2.5*b

100 loops, best of 3: 15.9 ms per loop


In [12]:
%timeit ne.evaluate('a*b-4.1*a > 2.5*b')

100 loops, best of 3: 3.13 ms per loop


### (some) preliminary conclusions

* numexpr is (generally) slow with small arrays
* numexpr is very fast with large arrays and complex operations
* numpy is terrific with in-place operations

# NumExpr supported Datatypes

* 8-bit boolean (bool)
* 32-bit signed integer (int or int32)
* 64-bit signed integer (long or int64)
* 32-bit single-precision floating point number (float or float32)
* 64-bit, double-precision floating point number (double or float64)
* 2x64-bit, double-precision complex number (complex or complex128)
* Raw string of bytes (str)